/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor.cliente;

import java.awt.Point;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import servidor.persistencia.AccesoPersistencia;

/**
 *
 * @author gonza
 */
public class VentanaCrearPrueba extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCrearPrueba
     */
    
    
    private void inicializarVectores () {
    
        // inicializar en 0 vector de codigo de preguntas seleccionadas por el usuario
        
        for ( int i=0; i<CANTPREG; i++) {
        
            this.codPreguntas[i] = 0;
            this.puntajePreg[i] = 0;
        
            }
      
                    
        // inicializar el vector que contiene los códigos de todas las preguntas persistidas en el banco 
        
        AccesoPersistencia instancia = AccesoPersistencia.getInstancia();
        vecCodPreguntas = instancia.devolverCodigoPreguntasDocente(5000000);
    
    }
    
    public VentanaCrearPrueba() {
        initComponents();
        inicializarVectores();   // inicializa variables vectores
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomPrueba = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoNomPreg1 = new javax.swing.JTextField();
        campoNomPreg2 = new javax.swing.JTextField();
        campoNomPreg3 = new javax.swing.JTextField();
        campoNomPreg4 = new javax.swing.JTextField();
        campoNomPreg5 = new javax.swing.JTextField();
        campoNomPreg6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        campoTipoPreg2 = new javax.swing.JTextField();
        campoTipoPreg3 = new javax.swing.JTextField();
        campoTipoPreg4 = new javax.swing.JTextField();
        campoTipoPreg5 = new javax.swing.JTextField();
        campoTipoPreg6 = new javax.swing.JTextField();
        campoTipoPreg1 = new javax.swing.JTextField();
        puntajePregunta1 = new javax.swing.JTextField();
        puntajePregunta2 = new javax.swing.JTextField();
        puntajePregunta3 = new javax.swing.JTextField();
        puntajePregunta4 = new javax.swing.JTextField();
        puntajePregunta5 = new javax.swing.JTextField();
        puntajePregunta6 = new javax.swing.JTextField();
        panelBotonesAgregarYCrear = new javax.swing.JPanel();
        botonAgregarPregunta1 = new javax.swing.JButton();
        botonAgregarPregunta2 = new javax.swing.JButton();
        botonCrearPregunta1 = new javax.swing.JButton();
        botonCrearPregunta2 = new javax.swing.JButton();
        botonAgregarPregunta3 = new javax.swing.JButton();
        botonAgregarPregunta4 = new javax.swing.JButton();
        botonAgregarPregunta5 = new javax.swing.JButton();
        botonAgregarPregunta6 = new javax.swing.JButton();
        botonCrearPregunta3 = new javax.swing.JButton();
        botonCrearPregunta4 = new javax.swing.JButton();
        botonCrearPregunta5 = new javax.swing.JButton();
        botonCrearPregunta6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ventMostrarPreguntasDocente = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPreguntasDocente = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        puntajeTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear prueba");

        jLabel1.setText("Nombre de la prueba");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(nomPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLabel5.setText("1");

        jLabel6.setText("2");
        jLabel6.setToolTipText("");

        jLabel7.setText("3");
        jLabel7.setToolTipText("");

        jLabel8.setText("4");
        jLabel8.setToolTipText("");

        jLabel9.setText("5");
        jLabel9.setToolTipText("");

        jLabel10.setText("6");
        jLabel10.setToolTipText("");

        campoNomPreg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomPreg3ActionPerformed(evt);
            }
        });

        campoTipoPreg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoPreg2ActionPerformed(evt);
            }
        });

        campoTipoPreg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoPreg5ActionPerformed(evt);
            }
        });

        puntajePregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta1ActionPerformed(evt);
            }
        });

        puntajePregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta2ActionPerformed(evt);
            }
        });

        puntajePregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta3ActionPerformed(evt);
            }
        });

        puntajePregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta4ActionPerformed(evt);
            }
        });

        puntajePregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta5ActionPerformed(evt);
            }
        });

        puntajePregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajePregunta6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTipoPreg1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(campoTipoPreg2)
                    .addComponent(campoTipoPreg3)
                    .addComponent(campoTipoPreg4)
                    .addComponent(campoTipoPreg5)
                    .addComponent(campoTipoPreg6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(puntajePregunta2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntajePregunta3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntajePregunta4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntajePregunta5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntajePregunta6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(puntajePregunta1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTipoPreg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntajePregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        botonAgregarPregunta1.setText("Agregar");
        botonAgregarPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta1ActionPerformed(evt);
            }
        });

        botonAgregarPregunta2.setText("Agregar");
        botonAgregarPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta2ActionPerformed(evt);
            }
        });

        botonCrearPregunta1.setText("Crear");
        botonCrearPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta1ActionPerformed(evt);
            }
        });

        botonCrearPregunta2.setText("Crear");
        botonCrearPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta2ActionPerformed(evt);
            }
        });

        botonAgregarPregunta3.setText("Agregar");
        botonAgregarPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta3ActionPerformed(evt);
            }
        });

        botonAgregarPregunta4.setText("Agregar");
        botonAgregarPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta4ActionPerformed(evt);
            }
        });

        botonAgregarPregunta5.setText("Agregar");
        botonAgregarPregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta5ActionPerformed(evt);
            }
        });

        botonAgregarPregunta6.setText("Agregar");
        botonAgregarPregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPregunta6ActionPerformed(evt);
            }
        });

        botonCrearPregunta3.setText("Crear");
        botonCrearPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta3ActionPerformed(evt);
            }
        });

        botonCrearPregunta4.setText("Crear");
        botonCrearPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta4ActionPerformed(evt);
            }
        });

        botonCrearPregunta5.setText("Crear");
        botonCrearPregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta5ActionPerformed(evt);
            }
        });

        botonCrearPregunta6.setText("Crear");
        botonCrearPregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPregunta6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesAgregarYCrearLayout = new javax.swing.GroupLayout(panelBotonesAgregarYCrear);
        panelBotonesAgregarYCrear.setLayout(panelBotonesAgregarYCrearLayout);
        panelBotonesAgregarYCrearLayout.setHorizontalGroup(
            panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addComponent(botonAgregarPregunta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCrearPregunta1))
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addComponent(botonAgregarPregunta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCrearPregunta2))
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(botonAgregarPregunta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCrearPregunta3))
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addComponent(botonAgregarPregunta4)
                        .addGap(12, 12, 12)
                        .addComponent(botonCrearPregunta4))
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addComponent(botonAgregarPregunta5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCrearPregunta5))
                    .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                        .addComponent(botonAgregarPregunta6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCrearPregunta6)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelBotonesAgregarYCrearLayout.setVerticalGroup(
            panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesAgregarYCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta1)
                    .addComponent(botonCrearPregunta1))
                .addGap(33, 33, 33)
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta2)
                    .addComponent(botonCrearPregunta2))
                .addGap(29, 29, 29)
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta3)
                    .addComponent(botonCrearPregunta3))
                .addGap(29, 29, 29)
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta4)
                    .addComponent(botonCrearPregunta4))
                .addGap(33, 33, 33)
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta5)
                    .addComponent(botonCrearPregunta5))
                .addGap(30, 30, 30)
                .addGroup(panelBotonesAgregarYCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarPregunta6)
                    .addComponent(botonCrearPregunta6))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel2.setText("Pregunta");

        jLabel3.setText("Nombre");

        jLabel4.setText("Tipo");

        jLabel12.setText("Puntaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel3)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel4)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel12)
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNomPreg5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(campoNomPreg4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoNomPreg3)
                                    .addComponent(campoNomPreg6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoNomPreg2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                    .addComponent(campoNomPreg1))))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 9, Short.MAX_VALUE)
                .addComponent(panelBotonesAgregarYCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoNomPreg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(campoNomPreg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(campoNomPreg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoNomPreg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(campoNomPreg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoNomPreg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBotonesAgregarYCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        ventMostrarPreguntasDocente.setBackground(new java.awt.Color(255, 255, 255));
        ventMostrarPreguntasDocente.setBorder(new javax.swing.border.MatteBorder(null));
        ventMostrarPreguntasDocente.setTitle("Preguntas de docente");
        ventMostrarPreguntasDocente.setVisible(true);

        tablaPreguntasDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaPreguntasDocente.setGridColor(new java.awt.Color(255, 255, 255));
        tablaPreguntasDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPreguntasDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPreguntasDocente);

        javax.swing.GroupLayout ventMostrarPreguntasDocenteLayout = new javax.swing.GroupLayout(ventMostrarPreguntasDocente.getContentPane());
        ventMostrarPreguntasDocente.getContentPane().setLayout(ventMostrarPreguntasDocenteLayout);
        ventMostrarPreguntasDocenteLayout.setHorizontalGroup(
            ventMostrarPreguntasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventMostrarPreguntasDocenteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        ventMostrarPreguntasDocenteLayout.setVerticalGroup(
            ventMostrarPreguntasDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventMostrarPreguntasDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLabel11.setText("Puntaje total:");

        puntajeTotal.setEditable(false);
        puntajeTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajeTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(botonGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(puntajeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ventMostrarPreguntasDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(puntajeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ventMostrarPreguntasDocente)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarFilasTabla(JTable tabla,int filas) {
    
        DefaultTableModel modeloTabla =  (DefaultTableModel) tabla.getModel(); // se agregan filas a la tabla
        modeloTabla.setRowCount(filas);
    };
    
    private void mostrarPreguntasDocente() {
    
        AccesoPersistencia accesoPersistencia = AccesoPersistencia.getInstancia();    
        List <String> preguntas =  accesoPersistencia.devolverPreguntasDocente(5000000); 
       
        agregarFilasTabla(this.tablaPreguntasDocente,0);
        agregarFilasTabla(this.tablaPreguntasDocente,preguntas.size());
       
      //  this.tablaPreguntasDocente.setValueAt("Programacion",0,0);
       // this.tablaPreguntasDocente.setValueAt("Multiple Opcion",0,1);
        
        Iterator it = preguntas.iterator();
        int fila = 0;
        while(it.hasNext()) {
            String  pregunta = (String) it.next(); //Aqui tomamos la clase del cliente
            this.tablaPreguntasDocente.setValueAt(pregunta,fila,0);
            this.tablaPreguntasDocente.setValueAt("Multiple Opcion",fila,1);
            fila++;
        }
    }    
    
    private void botonAgregarPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta1ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 1;
        mostrarPreguntasDocente();
       
        
       
    }//GEN-LAST:event_botonAgregarPregunta1ActionPerformed

    private void campoTipoPreg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoPreg2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoPreg2ActionPerformed

    private void campoNomPreg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomPreg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomPreg3ActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    
    boolean hayPreguntasSinCompletar() {
    
         if (this.campoNomPreg1.getText().length() == 0)
            return true;
    
        return false;
    
    }
    
    boolean hayPreguntasSinPuntaje() {
    
         if (this.puntajePregunta1.getText().length() == 0){
            return true;
         }
    
         if (this.puntajePregunta2.getText().length() == 0){
            return true;
         }
         
         if (this.puntajePregunta3.getText().length() == 0){
            return true;
         }
         
         if (this.puntajePregunta4.getText().length() == 0){
            return true;
         }
         
         if (this.puntajePregunta5.getText().length() == 0){
            return true;
         }
         
         if (this.puntajePregunta6.getText().length() == 0){
            return true;
         }
         
         return false;
    }
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        
        if (hayPreguntasSinCompletar()) {
            JOptionPane.showMessageDialog(this, "Faltan completar preguntas");
            return;
        }
        
        if (hayPreguntasSinPuntaje()) {
            JOptionPane.showMessageDialog(this, "Todas las preguntas tienen que tener puntaje");
            return;
        }
        
        AccesoPersistencia instancia = AccesoPersistencia.getInstancia();
        instancia.guardarPruebas(5000000,this.nomPrueba.getText(), this.codPreguntas, this.puntajePreg);
        instancia.listarPruebas();
        System.out.print(" codigo mayor " + instancia.devolverMaxCodEntidadPrueba1());
        
        JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
        dispose();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void campoTipoPreg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoPreg5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoPreg5ActionPerformed

    
    // muestra en el campo de la pregunta activa, la eleccion hecha en la tabla
    private void mostrarOpcionElegidaEnTabla (int preguntaActiva, int filaClick, String tipoPregunta) {
    
        
        switch (preguntaActiva) {
            case 1:
                this.campoNomPreg1.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg1.setText(tipoPregunta);
                break;
             
            case 2:
                this.campoNomPreg2.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg2.setText(tipoPregunta);
                break;
                
            case 3:
                this.campoNomPreg3.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg3.setText(tipoPregunta);
                break;    
                
            case 4:
                this.campoNomPreg4.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg4.setText(tipoPregunta);
                break;    
                
            case 5:
                this.campoNomPreg5.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg5.setText(tipoPregunta);
                break;    
                
            case 6:
                this.campoNomPreg6.setText(this.tablaPreguntasDocente.getValueAt(filaClick, 0).toString());
                this.campoTipoPreg6.setText(tipoPregunta);
                break;    
            default: break;    
                
                
            }
    
    }
    
    private void tablaPreguntasDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPreguntasDocenteMouseClicked
        // TODO add your handling code here:
        
         Point p = evt.getPoint();
         int fila = this.tablaPreguntasDocente.rowAtPoint(p); // fila donde se hizo click con el mouse
         
         
         mostrarOpcionElegidaEnTabla (preguntaActiva,fila,"Multiple opcion" );
         
         this.codPreguntas[preguntaActiva - 1] = this.vecCodPreguntas.get(fila);// guardar código de pregunta seleccionada
         
       //  System.out.println("Codigo de pregunta seleccionada: " + this.codPreguntas[preguntaActiva - 1]);
        // System.out.println("Numero de pregunta en la prueba: " + preguntaActiva );
        
    }//GEN-LAST:event_tablaPreguntasDocenteMouseClicked

    private void botonAgregarPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta2ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 2;
        mostrarPreguntasDocente();
    }//GEN-LAST:event_botonAgregarPregunta2ActionPerformed

    private void botonAgregarPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta3ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 3;
        mostrarPreguntasDocente();
    }//GEN-LAST:event_botonAgregarPregunta3ActionPerformed

    private void botonAgregarPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta4ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 4;
        mostrarPreguntasDocente();
    }//GEN-LAST:event_botonAgregarPregunta4ActionPerformed

    private void botonAgregarPregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta5ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 5;
        mostrarPreguntasDocente();
    }//GEN-LAST:event_botonAgregarPregunta5ActionPerformed

    private void botonAgregarPregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPregunta6ActionPerformed
        // TODO add your handling code here:
        preguntaActiva = 6;
        mostrarPreguntasDocente();
    }//GEN-LAST:event_botonAgregarPregunta6ActionPerformed

    private void botonCrearPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta1ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta1ActionPerformed

    private void botonCrearPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta2ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta2ActionPerformed

    private void botonCrearPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta3ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta3ActionPerformed

    private void botonCrearPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta4ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta4ActionPerformed

    private void botonCrearPregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta5ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta5ActionPerformed

    private void botonCrearPregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPregunta6ActionPerformed
        // TODO add your handling code here:
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
    }//GEN-LAST:event_botonCrearPregunta6ActionPerformed

    private void puntajeTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajeTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntajeTotalActionPerformed

    private void mostrarPuntajeTotal(int puntajePregunta) {
    
        int puntTotal = 0;
      
       // int[] puntajePreg  = new int[CANTPREG]; 
               
        
       
        
        if (this.puntajePregunta1.getText().length() == 0) 
            this.puntajePreg[0] = 0;
        else
            this.puntajePreg[0] = Integer.parseInt(this.puntajePregunta1.getText()); 
        
      
        if (this.puntajePregunta2.getText().length() == 0) 
            this.puntajePreg[1] = 0;
        else
            this.puntajePreg[1] = Integer.parseInt(this.puntajePregunta2.getText()); 
        
        if (this.puntajePregunta3.getText().length() == 0) 
            this.puntajePreg[2] = 0;
        else
            this.puntajePreg[2] = Integer.parseInt(this.puntajePregunta3.getText()); 
        
        
        if (this.puntajePregunta4.getText().length() == 0) 
            this.puntajePreg[3] = 0;
        else
            this.puntajePreg[3] = Integer.parseInt(this.puntajePregunta4.getText()); 
        
    
        if (this.puntajePregunta5.getText().length() == 0) 
            this.puntajePreg[4] = 0;
        else
            this.puntajePreg[4] = Integer.parseInt(this.puntajePregunta5.getText()); 
        
      
        if (this.puntajePregunta6.getText().length() == 0) 
            this.puntajePreg[5] = 0;
        else
            this.puntajePreg[5] = Integer.parseInt(this.puntajePregunta6.getText()); 
            
      
      
        
        for (int i=0; i < CANTPREG; i++)
            puntTotal = puntTotal + this.puntajePreg[i];
        
        this.puntajeTotal.setText(Integer.toString(puntTotal));// mostrar  puntaje total
    }
    
    private void puntajePregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta1ActionPerformed
        // TODO add your handling code here:
        mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta1.getText()));
        
    }//GEN-LAST:event_puntajePregunta1ActionPerformed

    private void puntajePregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta2ActionPerformed
        // TODO add your handling code here:
        mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta2.getText()));
    }//GEN-LAST:event_puntajePregunta2ActionPerformed

    private void puntajePregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta3ActionPerformed
        // TODO add your handling code here:
        mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta3.getText()));
    }//GEN-LAST:event_puntajePregunta3ActionPerformed

    private void puntajePregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta4ActionPerformed
        // TODO add your handling code here:
        mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta4.getText()));
    }//GEN-LAST:event_puntajePregunta4ActionPerformed

    private void puntajePregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta5ActionPerformed
        // TODO add your handling code here:
         mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta5.getText()));
        
    }//GEN-LAST:event_puntajePregunta5ActionPerformed

    private void puntajePregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajePregunta6ActionPerformed
        // TODO add your handling code here:
         mostrarPuntajeTotal (Integer.parseInt(this.puntajePregunta6.getText()));
    }//GEN-LAST:event_puntajePregunta6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearPrueba().setVisible(true);
            }
        });
    }

    private int preguntaActiva;     // guarda la pregunta que está siendo elegida
    final int CANTPREG = 6;   // constante para la cantidad de preguntas de una prueba
    
    private int[] codPreguntas =  new int[CANTPREG];
    private int[] puntajePreg = new int [CANTPREG];
   
    ArrayList<Integer> vecCodPreguntas;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPregunta1;
    private javax.swing.JButton botonAgregarPregunta2;
    private javax.swing.JButton botonAgregarPregunta3;
    private javax.swing.JButton botonAgregarPregunta4;
    private javax.swing.JButton botonAgregarPregunta5;
    private javax.swing.JButton botonAgregarPregunta6;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCrearPregunta1;
    private javax.swing.JButton botonCrearPregunta2;
    private javax.swing.JButton botonCrearPregunta3;
    private javax.swing.JButton botonCrearPregunta4;
    private javax.swing.JButton botonCrearPregunta5;
    private javax.swing.JButton botonCrearPregunta6;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField campoNomPreg1;
    private javax.swing.JTextField campoNomPreg2;
    private javax.swing.JTextField campoNomPreg3;
    private javax.swing.JTextField campoNomPreg4;
    private javax.swing.JTextField campoNomPreg5;
    private javax.swing.JTextField campoNomPreg6;
    private javax.swing.JTextField campoTipoPreg1;
    private javax.swing.JTextField campoTipoPreg2;
    private javax.swing.JTextField campoTipoPreg3;
    private javax.swing.JTextField campoTipoPreg4;
    private javax.swing.JTextField campoTipoPreg5;
    private javax.swing.JTextField campoTipoPreg6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomPrueba;
    private javax.swing.JPanel panelBotonesAgregarYCrear;
    private javax.swing.JTextField puntajePregunta1;
    private javax.swing.JTextField puntajePregunta2;
    private javax.swing.JTextField puntajePregunta3;
    private javax.swing.JTextField puntajePregunta4;
    private javax.swing.JTextField puntajePregunta5;
    private javax.swing.JTextField puntajePregunta6;
    private javax.swing.JTextField puntajeTotal;
    private javax.swing.JTable tablaPreguntasDocente;
    private javax.swing.JInternalFrame ventMostrarPreguntasDocente;
    // End of variables declaration//GEN-END:variables
}
