/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor.cliente;

/**
 *
 * @author gonza
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        menuDocente = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        opDocenteCrearPregunta = new javax.swing.JMenuItem();
        opDocenteCrearPrueba = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuAsignarPrueba = new javax.swing.JMenuItem();
        menuAlumno = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Repositorio de Evaluaciones");

        menuAdministrador.setText("Administrador");
        jMenuBar1.add(menuAdministrador);

        menuDocente.setText("Docente");

        jMenu1.setText("Crear");

        opDocenteCrearPregunta.setText("Pregunta");
        opDocenteCrearPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDocenteCrearPreguntaActionPerformed(evt);
            }
        });
        jMenu1.add(opDocenteCrearPregunta);

        opDocenteCrearPrueba.setText("Prueba");
        opDocenteCrearPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDocenteCrearPruebaActionPerformed(evt);
            }
        });
        jMenu1.add(opDocenteCrearPrueba);

        menuDocente.add(jMenu1);

        jMenu2.setText("Modificar");
        menuDocente.add(jMenu2);

        jMenu3.setText("Borrar");
        menuDocente.add(jMenu3);

        menuAsignarPrueba.setText("Asignar prueba");
        menuAsignarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignarPruebaActionPerformed(evt);
            }
        });
        menuDocente.add(menuAsignarPrueba);

        jMenuBar1.add(menuDocente);

        menuAlumno.setText("Alumno");
        jMenuBar1.add(menuAlumno);

        menuSalir.setText("Salir");
        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1101, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opDocenteCrearPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDocenteCrearPreguntaActionPerformed
        // TODO add your handling code here:
        
        VentanaCrearPregunta v = new VentanaCrearPregunta();
        v.setVisible(true);
        
        
    }//GEN-LAST:event_opDocenteCrearPreguntaActionPerformed

    private void opDocenteCrearPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDocenteCrearPruebaActionPerformed
        // TODO add your handling code here:
        VentanaCrearPrueba v = new VentanaCrearPrueba();
        v.setVisible(true);
    }//GEN-LAST:event_opDocenteCrearPruebaActionPerformed

    private void menuAsignarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignarPruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAsignarPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuItem menuAsignarPrueba;
    private javax.swing.JMenu menuDocente;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem opDocenteCrearPregunta;
    private javax.swing.JMenuItem opDocenteCrearPrueba;
    // End of variables declaration//GEN-END:variables
}
