/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor.cliente;

import java.util.Enumeration;
import static javafx.application.Platform.exit;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import servidor.persistencia.AccesoPersistencia;



/**
 *
 * @author gonza
 */
public class VentanaCrearPregunta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCrearPregunta
     */
    
    
    public VentanaCrearPregunta() {
        initComponents();
        
        this.panelVerdaderFalso.setVisible(false);  // ocultar panel verdadero falso
        this.panelMultipleOpcion.setVisible(false); // ocultar panel multiple opcion
        
                                                           // grupo de botones para la pregunta múltiple opción
        this.botonesMultipleOpcion.add(op1MultipleOpcion);
        this.botonesMultipleOpcion.add(op2MultipleOpcion);
        this.botonesMultipleOpcion.add(op3MultipleOpcion);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesMultipleOpcion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoEnunciado = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tipoPregunta = new javax.swing.JComboBox<>();
        panelVerdaderFalso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        opCorrectaVerdFalso = new javax.swing.JComboBox<>();
        panelMultipleOpcion = new javax.swing.JPanel();
        mensMultipleOpcion = new javax.swing.JLabel();
        mensOpcion1 = new javax.swing.JLabel();
        mensOpcion2 = new javax.swing.JLabel();
        mensOpcion3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        opcion1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        opcion2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        opcion3 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        op1MultipleOpcion = new javax.swing.JRadioButton();
        op2MultipleOpcion = new javax.swing.JRadioButton();
        op3MultipleOpcion = new javax.swing.JRadioButton();
        botonCancelar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Pregunta");

        jLabel1.setText("Nombre");

        jLabel2.setText("Enunciado");

        campoEnunciado.setColumns(20);
        campoEnunciado.setRows(5);
        jScrollPane1.setViewportView(campoEnunciado);

        jLabel3.setText("Tipo de pregunta");

        tipoPregunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Verdadero - Falso", "Multiple Opcion" }));
        tipoPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPreguntaActionPerformed(evt);
            }
        });

        panelVerdaderFalso.setBorder(javax.swing.BorderFactory.createTitledBorder("Verdadero - Falso"));

        jLabel4.setText("Opción correccta");

        opCorrectaVerdFalso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Verdadero", "Falso" }));

        javax.swing.GroupLayout panelVerdaderFalsoLayout = new javax.swing.GroupLayout(panelVerdaderFalso);
        panelVerdaderFalso.setLayout(panelVerdaderFalsoLayout);
        panelVerdaderFalsoLayout.setHorizontalGroup(
            panelVerdaderFalsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerdaderFalsoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(opCorrectaVerdFalso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelVerdaderFalsoLayout.setVerticalGroup(
            panelVerdaderFalsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerdaderFalsoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelVerdaderFalsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(opCorrectaVerdFalso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mensMultipleOpcion.setText("Multiple Opción");

        mensOpcion1.setText("Opción 1");

        mensOpcion2.setText("Opción 2");

        mensOpcion3.setText("Opción 3");

        opcion1.setColumns(20);
        opcion1.setRows(5);
        jScrollPane2.setViewportView(opcion1);

        opcion2.setColumns(20);
        opcion2.setRows(5);
        jScrollPane3.setViewportView(opcion2);

        opcion3.setColumns(20);
        opcion3.setRows(5);
        jScrollPane4.setViewportView(opcion3);

        jLabel5.setText("Opcion correcta");

        op1MultipleOpcion.setText("1");

        op2MultipleOpcion.setText("2");

        op3MultipleOpcion.setText("3");
        op3MultipleOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3MultipleOpcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op2MultipleOpcion)
                            .addComponent(op1MultipleOpcion)
                            .addComponent(op3MultipleOpcion))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(op1MultipleOpcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(op2MultipleOpcion)
                .addGap(27, 27, 27)
                .addComponent(op3MultipleOpcion)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout panelMultipleOpcionLayout = new javax.swing.GroupLayout(panelMultipleOpcion);
        panelMultipleOpcion.setLayout(panelMultipleOpcionLayout);
        panelMultipleOpcionLayout.setHorizontalGroup(
            panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensMultipleOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                            .addComponent(mensOpcion1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMultipleOpcionLayout.createSequentialGroup()
                            .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mensOpcion2)
                                .addComponent(mensOpcion3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                                .addComponent(jScrollPane4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMultipleOpcionLayout.setVerticalGroup(
            panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                        .addComponent(mensMultipleOpcion)
                        .addGap(18, 18, 18)
                        .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensOpcion1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensOpcion2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelMultipleOpcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMultipleOpcionLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(mensOpcion3)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelVerdaderFalso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelMultipleOpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(86, 86, 86)
                                .addComponent(tipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 436, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(243, 243, 243)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelMultipleOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(panelVerdaderFalso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPreguntaActionPerformed
        // TODO add your handling code here: 
        // este evento registra cuando se elige una opción del tipo de pregunta
        
        String preguntaSeleccionada = (String) this.tipoPregunta.getSelectedItem();  // guarda la opcion seleccionada
        
        if (preguntaSeleccionada.equals ("Verdadero - Falso")) 
        {
            this.panelMultipleOpcion.setVisible(false);
            this.panelVerdaderFalso.setVisible(true);
        }    
        else if (preguntaSeleccionada.equals("Multiple Opcion"))
        {
            this.panelVerdaderFalso.setVisible(false);
            this.panelMultipleOpcion.setVisible(true);
        }    
    }//GEN-LAST:event_tipoPreguntaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here: 
            
            
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void op3MultipleOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3MultipleOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op3MultipleOpcionActionPerformed

    
    
    // guarda las preguntas en la EntidadPregunta_MO y las respuestas en la EntidadRespuesta_MO 
        private void persistirMultipleOpcion(long cedIdent, String nombre, String enunciado, int opCorrecta) {
    
        AccesoPersistencia accesoPersistencia = AccesoPersistencia.getInstancia();
        
        int maxPK =accesoPersistencia.devolverMaxCodEntidadPregunta();  //  devuelve la maxima clave primaria      
       
        accesoPersistencia.guardarPregunta(cedIdent, ++maxPK,nombre, enunciado); // guardar preguntas
        
        
        // guardar respuestas
        for (int i = 1; i < CANT_OPC_RESPMO + 1 ; i++) {
            boolean respCorrecta = false;            
            if (i == opCorrecta)   // el boton i es la respuesta correcta
                respCorrecta = true;
            
            switch (i) {
                case 1: accesoPersistencia.guardarRespuestasMultipleOpcion(cedIdent,maxPK,i,this.opcion1.getText(),respCorrecta);
                        break;
                case 2: accesoPersistencia.guardarRespuestasMultipleOpcion(cedIdent,maxPK,i,this.opcion2.getText(),respCorrecta);
                        break;        
                case 3: accesoPersistencia.guardarRespuestasMultipleOpcion(cedIdent,maxPK,i,this.opcion3.getText(),respCorrecta);
                        break;        
                default:
                        break;
                   
            }
            //System.out.println(cedIdent + maxPK + " " + i +" " +this.opcion1.getText() + " " + respCorrecta);
        }
    
        accesoPersistencia.listarRespuestasMO_EnTerminal();
    };
    
    
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        int opcionPresionada = 0;
        boolean respCorrectaVF = true;  // guarda la respuesta correcta en la pregunta verdadero-falso.
        
      
       
       if (this.campoNombre.getText().length() == 0){
            JOptionPane.showMessageDialog(this,  "Debe ingresar un nombre para la pregunta");
            return;
            }
       
       if (this.campoEnunciado.getText().length() == 0){
            JOptionPane.showMessageDialog(this,  "Debe ingresar un enunciado para la pregunta");
            return;    
            }
        
        // si pregunta elegida es Multiple Opcion
        if (this.tipoPregunta.getSelectedItem().equals("Multiple Opcion"))  
            {                                                                          // guardar opcion verdadera
               if ( (this.opcion1.getText().length() == 0) || (this.opcion2.getText().length() == 0) || (this.opcion3.getText().length() == 0))
               {
                   JOptionPane.showMessageDialog(this, "Debe ingresar una opción para la respuesta");
                   return;
                 
               }
            
                if (this.op1MultipleOpcion.isSelected())
                    opcionPresionada = 1;
                else if (this.op2MultipleOpcion.isSelected())
                    opcionPresionada = 2;
                else if (this.op3MultipleOpcion.isSelected())
                    opcionPresionada = 3;
                else
                    {
                    JOptionPane.showMessageDialog(this,  "Debe seleccionar una opción verdadera");
                    return;
                    }
               
                persistirMultipleOpcion(5000000, this.campoNombre.getText(), this.campoEnunciado.getText(), opcionPresionada);
               // System.out.print("nombre" + this.campoNombre.getText() + " enunciado " + this.campoEnunciado.getText());
            } 
      
        
        // si pregunta elegida es verdadero-falso
        else if (this.tipoPregunta.getSelectedItem().equals("Verdadero - Falso"))  
            {                                                                               // guardar opcion correcta
                if (this.opCorrectaVerdFalso.getSelectedItem().equals("Verdadero"))
                    
                    respCorrectaVF = true;
                               
                else if (this.opCorrectaVerdFalso.getSelectedItem().equals("Falso"))
                   
                    respCorrectaVF = false;
                   
                else {
                    JOptionPane.showMessageDialog(this,  "Debe seleccionar la respuesta correcta");
                    return;
                     }
            }    
      
        else  { // ninguna pregunta seleccionada 
           
               JOptionPane.showMessageDialog(this,  "Debe seleccionar una pregunta");
               return; 
               }
        
        JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
        dispose();
    }//GEN-LAST:event_botonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearPregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearPregunta().setVisible(true);
            }
        });
    }

    
   private final int CANT_OPC_RESPMO = 3;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.ButtonGroup botonesMultipleOpcion;
    private javax.swing.JTextArea campoEnunciado;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel mensMultipleOpcion;
    private javax.swing.JLabel mensOpcion1;
    private javax.swing.JLabel mensOpcion2;
    private javax.swing.JLabel mensOpcion3;
    private javax.swing.JRadioButton op1MultipleOpcion;
    private javax.swing.JRadioButton op2MultipleOpcion;
    private javax.swing.JRadioButton op3MultipleOpcion;
    private javax.swing.JComboBox<String> opCorrectaVerdFalso;
    private javax.swing.JTextArea opcion1;
    private javax.swing.JTextArea opcion2;
    private javax.swing.JTextArea opcion3;
    private javax.swing.JPanel panelMultipleOpcion;
    private javax.swing.JPanel panelVerdaderFalso;
    private javax.swing.JComboBox<String> tipoPregunta;
    // End of variables declaration//GEN-END:variables
}
